version: 0.2
phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"

  pre_build:
    commands:
      - mvn clean install
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=715483467916.dkr.ecr.ap-southeast-1.amazonaws.com/pathwayschoolapp
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t pathwayschoolapp .
      - docker tag pathwayschoolapp:latest 715483467916.dkr.ecr.ap-southeast-1.amazonaws.com/pathwayschoolapp:latest
      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images..
      - docker push 715483467916.dkr.ecr.ap-southeast-1.amazonaws.com/pathwayschoolapp:latest
artifacts:
  files:
    - 'Dockerfile'
    - 'target/PathwayEnrollmentProgram-1.0.0.jar'
cache:
  paths:
    - '/root/.m2/**/*'    